### ISSUE TITLE
Unknown bank account per transaction

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#10]
I think that the account that is connected with each transaction should be visible (or at least the bank)
![Screenshot 06_14_2022 15_07_40](https://user-images.githubusercontent.com/64831585/173573593-18c1334a-6324-4082-bca0-a76bbf9df259.png)

**Comment by chris-iliopoulos** [comment]
Duplicated by: https://github.com/squaredev-io/GFM-UAT/issues/24
