### ISSUE TITLE
Piraeus Bank - Auth page

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#121]
<img width="957" alt="Screenshot 2022-09-26 at 13 23 09" src="https://user-images.githubusercontent.com/97880493/192258645-55227e0c-41c1-4dc4-b1a0-60762847fa08.png">

@geikosipentakis you could come up with a UI/UX proposal for this...

(this is the Piraeus page of authentication after you connect the bank in GFM - the bank does not have its own page for this)

**Comment by geikosipentakis** [comment]
I have done 3 separate designs for the individual authentication screens in the link below:

https://www.figma.com/file/hl3biSsMK3Z8PlsCa8rLZs/GFM?node-id=736%3A541
