### ISSUE TITLE
Issues with forthcoming transactions

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#124]
![image](https://user-images.githubusercontent.com/64831585/192447575-f68a5526-4302-4cbb-809e-25ae335b8605.png)

1)There is no bank icon
2)There is no bank border to the left
3)I have chosen outgoing transactions, but the forthcoming transaction is an income transaction

**Comment by chris-iliopoulos** [comment]
I'm not sure that we want the bank information to show up in the upcoming transactions as they do in transactions that have already taken place ... @ksiabani what are your thoughts on that?

👍 about the filtering though

**Comment by ksiabani** [comment]
Upcoming transactions AFAIK are bank agnostic, so I don't think we have and can show this information.
