### ISSUE TITLE
Not active account after reconnection

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#126]
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/64831585/192525761-a9f19828-1d9f-4bcf-b4e3-f0aeacbf4c4a.png)
The user connected Alpha Bank and NBG. At first everything was ok. Then he tried to reconnect Alpha Bank in order to add a card. Now the result is the above. The alpha bank is "not active" and he cannot reconnect it. 

username : mskaltsounakis@softone.gr

**Comment by GeorgeVarvates** [comment]
We found out how this error occured. Do the following steps to reproduce the error

1. Complete connection to any bank (Alpha bank in my case)
2. Try to connect to another bank (Piraeus for example)
3. Don't complete connection to Piraeus bank and return back to GFM
4. Try to reconnect the bank of step1 
5. Complete the reconnection
6. Now Alpha Bank is not active
Furthermore it seems that it tries to connect to the bank from step 2
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/64831585/192704495-be827d4c-9bba-445d-8a69-e0b0d22801f5.png)

**Comment by chris-iliopoulos** [comment]
Thanks, will try this and let you know!

**Comment by chris-iliopoulos** [comment]
@GeorgeVarvates can you please confirm if this issue persists? Thank you.

**Comment by GeorgeVarvates** [comment]
ok

**Comment by GeorgeVarvates** [comment]
Cannot reproduce the error now.I guess it's ok
