### ISSUE TITLE
Missing transactions

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#127]
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/64831585/192526610-7476b15f-da40-4422-9edf-890e97da80b4.png)
The user connected Alpha Bank and NBG but he sees only the Alpha Bank transactions

username : mskaltsounakis@softone.gr

**Comment by chris-iliopoulos** [comment]
@GeorgeVarvates can you please confirm if this issue persists? Thank you.

**Comment by GeorgeVarvates** [comment]
Seems ok now
