### ISSUE TITLE
Wrong predictions

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#128]
![GetImageAttachment](https://user-images.githubusercontent.com/64831585/192527383-6c012de3-1bf0-4079-bcba-4dadb52caf24.png)

The user has connected three banks
She sees the above image which is not right
Wrong current month, no predictions , wrong numbers

userId:6332b1248f9afd71cdb53a0b

**Comment by awareness481** [comment]
This happens when we a new user is created & the predictions haven't been generated yet. We shouldn't be trying to show predictions when there aren't any :P

**Comment by chris-iliopoulos** [comment]
This is too weird ... how can we reproduce it?

**Comment by chris-iliopoulos** [comment]
> This happens when we a new user is created & the predictions haven't been generated yet. We shouldn't be trying to show predictions when there aren't any :P

I don't think we show predictions when there's no cashflow but we should check this

**Comment by awareness481** [comment]
> > This happens when we a new user is created & the predictions haven't been generated yet. We shouldn't be trying to show predictions when there aren't any :P
> 
> I don't think we show predictions when there's no cashflow but we should check this

Verified it earlier today, that's the issue. Will not be hard to fix ^^
