### ISSUE TITLE
Add new GFM Logo

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#129]
[GO_Finance_Manager_logo.pdf](https://github.com/squaredev-io/GFM-UAT/files/9657088/GO_Finance_Manager_logo.pdf)

**Comment by awareness481** [comment]
Do we have any other details/instructions about this?

**Comment by chris-iliopoulos** [comment]
You're right I didn't include any more details for some reason ... The guideline is that we use the horizontal logo (the one on the right) for the web app and we should apply it on the page where we have the current GFM 'logo' top left. We have yet to receive some feedback on the mobile version.
