### ISSUE TITLE
Questions about consent status

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#13]
How do i know that the consent is still active? If the consent ends (after 3 months) how do i renew it?
![image](https://user-images.githubusercontent.com/64831585/173796889-0b63acff-4642-4fc5-82af-4d1e4212a623.png)

**Comment by chris-iliopoulos** [comment]
Changed this into a bug because the consents raise a question of when they expire as this creates an issue that prevents users from using the app's features (such as the Wallet and Transactions pages).

**Comment by sinnec** [comment]
@chris-iliopoulos If the scope of this issue is just for showing consent expiry date to the user, then it's solved by https://github.com/squaredev-io/gfm/pull/605

**Comment by chris-iliopoulos** [comment]
It probably is at this point ... but let's revisit the consent renewal in the near future.

**Comment by chris-iliopoulos** [comment]
The consent error handling along with the UX of the eligibility of the consent have been resolved as of now. I will close this issue and open Another issue about the consent's Expiration Date & a possible renewal feature.
