### ISSUE TITLE
Cannot skip reconnection

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#130]
![image](https://user-images.githubusercontent.com/64831585/192701286-7b519018-2592-4539-ba54-8b05851073d6.png)

It keeps asking me to reconnect my eurobank account. If i dont want to reconnect it now,i can't skip this screen

**Comment by chris-iliopoulos** [comment]
So this is working exactly as it was designed 🙃 ... the whole purpose of this is to force the user to reconnect the bank with the invalid consent to avoid stale data and wrong/outdated analytics.
