### ISSUE TITLE
Daily Balance graph does not show when there's no cashflow

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#132]

**Comment by chris-iliopoulos** [comment]
@ksiabani Need your opinion on this one ... Should we show the Daily Balance graph when there's no Cashflow yet (ergo no predictions) or should we hide it until the Cashflow has been successfully generated so we have valid data and predictions?

**Comment by ksiabani** [comment]
We need something like this:

![image](https://user-images.githubusercontent.com/3550488/194320538-b67941fa-188e-4c4f-91e5-e0ceb335d8c6.png)

Basically we show a blurry chart (or could be an image) with a message on top. 

An alternative could be to ask a suggestion from Giorgos Eikosipentakis

**Comment by chris-iliopoulos** [comment]
@awareness481

**Comment by awareness481** [comment]
Seems like it could work well. Will work on this soon
