### ISSUE TITLE
Not all transactions from all Banks are shown in filter 'All', but they are show in filters 'Incoming'/'Outgoing'

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#133]
Only when these transactions are not yet in the enriched!

**Comment by awareness481** [comment]
Haven't been able to reproduce this one so far 👀

**Comment by chris-iliopoulos** [comment]
Right now me neither ;p ... closing this for now! If something weird comes up we'll open an issue with more details!
