### ISSUE TITLE
When I enter the Budgeting page the language changes automatically from English to Greek

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#139]

**Comment by awareness481** [comment]
Any specific steps to reproduce this? I haven't been able to reproduce this on the staging or prod servers.

**Comment by chris-iliopoulos** [comment]
https://user-images.githubusercontent.com/97880493/195110305-2e06eded-a10f-41e6-89e0-25ffd7f781e0.mov

**Comment by awareness481** [comment]
That's weird 👀, this is on staging right?

**Comment by chris-iliopoulos** [comment]
> That's weird 👀, this is on staging right?

prod

**Comment by chris-iliopoulos** [comment]
cannot reproduce anymore
