### ISSUE TITLE
Wrong account balance

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#14]
The account balance is different from the real one. How often do you refresh the balances?
![image](https://user-images.githubusercontent.com/64831585/173826880-38d868ef-d7d1-4fea-a299-a587ffdf5f51.png)

**Comment by ghost** [comment]
After checking GFM it seems like the call to OFS is completed successfully without errors, meaning that the problem is OFS data being out of date.
