### ISSUE TITLE
Credit card transaction wrong sign on amount

### ISSUE THREAD

**Issue by sinnec** [squaredev-io/GFM-UAT#148]
Amounts in credit card expenses look positive though they should be negative

<img width="903" alt="Screenshot 2022-10-18 at 15 41 05" src="https://user-images.githubusercontent.com/48223149/196435060-a925ac8e-b0e2-4105-a87d-2e66e348d283.png">

**Comment by chris-iliopoulos** [comment]
@stavrostheocharis what's your opinion on this one? I think that since these are presented as expenses they should also be with a negative sign.
