### ISSUE TITLE
Missing card transactions

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#15]
I have some pending transactions on my credit card that are not visible on GFM transactions
The API returns these transactions

**Comment by chris-iliopoulos** [comment]
Do we show pending transactions? @ksiabani

**Comment by ksiabani** [comment]
This is a PSD 2 thing. Do the banks send pending transactions? Have no idea tbh. AFAIK we show what we get. The best here to comment is @stavrostheocharis I guess.

**Comment by GeorgeVarvates** [comment]
The endpoint cards/transactions returns all the transactions (even if they are pending). The problem here is that we can't stand out which transactions are completed and which are pending. Perhaps if we compare the account/transactions with the card/transactions

**Comment by stavrostheocharis** [comment]
This part is partially done for Alphabank and NBG. These two banks send both separated card transactions and the account transactions (the card transactions are "duplicated", they happen once on the card side and once on the account side). We already check them with a new field "duplicated_with" which can indicate if they have already happened on both sides.

The obstacle is for Piraeus and Eurobank where we get the transactions only once (if they happened through card, we get the card part, otherwise we get the account part).

**Comment by chris-iliopoulos** [comment]
But we don't get any 'transaction status' field ... so we won't be able to show this info. @GeorgeVarvates any thoughts on that?

**Comment by GeorgeVarvates** [comment]
In my opinion the issue is that GFM doesn't show at all these transactions. I agree that we don't have the status info, but the transaction doesn't appear at all even as completed.
If you want to show also the status, you can check if the transaction appears in both account and card transactions

**Comment by chris-iliopoulos** [comment]
If not all the banks answer the same data (eg ERB & Peiraios) this cannot be solved atm.

**Comment by sinnec** [comment]
<img width="1245" alt="Screenshot 2022-08-18 at 13 53 05" src="https://user-images.githubusercontent.com/48223149/185378579-cb6dd18d-1e4f-4b4e-9b62-1b44f28c0c1f.png">

The above credit card transactions seem completed from the Eurobank site but still haven't appeared in my transactions.

**Comment by chris-iliopoulos** [comment]
@stavrostheocharis I see that the basic transactions API in OFS does bring these card transactions from the bank ... but they are transactions without provider.id ... Does wyre handle these transactions in any specific way? Does it removes them as duplicates when they also exist in the account transactions list? Do we lose them altogether?

**Comment by chris-iliopoulos** [comment]
With the above problem solved (no providerId) we should proceed with these steps:
1. We should know when the transaction comes from a credit card so we show them in a correct manner in the Transactions List (amount is expense & the description which is not descriptive enough for some banks)
2. We should only keep the transactions from the accounts whenever there's duplicates (in the cards' transactions)
3. We should only show the debit card transactions when they don't exist inside the accounts' transactions.

**Comment by chris-iliopoulos** [comment]
This issue relates to: https://github.com/squaredev-io/GFM-UAT/issues/115 . When that is done we should close this as well if all cases are covered.

**Comment by chris-iliopoulos** [comment]
This issue relates to: https://github.com/squaredev-io/GFM-UAT/issues/115 . When that is done we should close this as well if all cases are covered.

**Comment by chris-iliopoulos** [comment]
@GeorgeVarvates can you please confirm if this issue persists? Thank you.

**Comment by GeorgeVarvates** [comment]
![image](https://user-images.githubusercontent.com/64831585/194822582-77e78482-0ce8-4d3c-92fd-61854b959cc2.png)
The first and the last transaction of the photo are the same transaction
Transaction 1 id : 6343cb8ac9f0350911efcdec
Transaction 2 id : 6343cb8ac9f0350911efcec4

**Comment by chris-iliopoulos** [comment]
Ok will check this one ... but do you have missing card transactions now or is this problem solved?

**Comment by GeorgeVarvates** [comment]
Currently i dont have any pending transactions to check. I will let you know

**Comment by GeorgeVarvates** [comment]
It seems ok now
