### ISSUE TITLE
BUDGET page -spending amount per category not updated

### ISSUE THREAD

**Issue by nikosdouv** [squaredev-io/GFM-UAT#152]
The spending amount per Budget cateogory (eg ΑΣΦΑΛΙΣΗ ΚΑΙ ΣΥΝΤΑΞΗ, ΛΟΓΑΡΙΑΣΜΟΙ ΚΟΙΝΗΣ ΟΦΕΛΕΙΑΣ, ΣΤΕΓΑΣΗ κτλ) is not updated from the respective transactions. For example, in 03/10 i have an expense marked as RENT (2000 EUR). The respective budget category HOUSING shows zero amount spent this month.

**Comment by nikosdouv** [comment]
![Screenshot_20221024_023031](https://user-images.githubusercontent.com/107864092/197523116-11b7529b-4a2d-4d5f-89b3-2d634e82179d.png)

**Comment by nikosdouv** [comment]
![Screenshot_20221024_021618](https://user-images.githubusercontent.com/107864092/197523207-9c6b8a10-893e-4554-a6c5-f2d4c2dd6010.png)

**Comment by chris-iliopoulos** [comment]
~~@nikosdouv την κατηγορία 'Ενοίκιο' στην συγκεκριμένη συναλλαγή την καταχώρησες εσύ με update ή την βρήκες εξ' αρχής έτσι?~~ Έπειτα από επιβεβαίωση - Η κατηγορία στην παραπάνω συναλλαγή προέρχεται από update.
