### ISSUE TITLE
ERP connection with different account fails

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#154]
I have an established erp connection. Then i try to connect with another user. The app keeps asking data for the previous user
![image](https://user-images.githubusercontent.com/64831585/197750239-2a17fbe9-2fa9-4dd1-bddf-c43107765a49.png)
check the url params
![image](https://user-images.githubusercontent.com/64831585/197750349-a9dc62c2-c0c9-4e15-8454-fdf42d867b35.png)
check the actual data that gfm sends

**Comment by chris-iliopoulos** [comment]
@GeorgeVarvates How can I reproduce this? I connected an ERP account with a new user, then logged out and logged in with another user but I couldn't see anything like this in the network requests.

**Comment by GeorgeVarvates** [comment]
Logged out from ERP connection or from GFM?

**Comment by chris-iliopoulos** [comment]
After discussion, we are talking about the same userId trying to connect different ERP accounts. This leads to an error and the original account being kept over the new one. Solution: always keep the latest account added.
