### ISSUE TITLE
Graphs not working properly when No Cashflow has been created.

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#155]

**Comment by chris-iliopoulos** [comment]
![Screenshot 2022-10-25 at 14 39 26](https://user-images.githubusercontent.com/97880493/197765680-fe05d4f7-f0cf-49c6-bea0-996928d73f7d.png)
![Screenshot 2022-10-25 at 14 39 37](https://user-images.githubusercontent.com/97880493/197765683-ce02a853-ea73-4f70-9042-d7ffc7e26568.png)
![Screenshot 2022-10-25 at 14 26 52](https://user-images.githubusercontent.com/97880493/197765771-794c3165-acec-483e-84bd-381167797db0.png)
![Screenshot 2022-10-25 at 14 28 11](https://user-images.githubusercontent.com/97880493/197765777-4e9d686d-0d2c-479f-ae9f-da136033c25b.png)

I think we broke this ... it was working just fine a couple of days back...

**Comment by awareness481** [comment]
Was this tested on prod or staging? Because we haven't released this on prod

**Comment by chris-iliopoulos** [comment]
We did a release (https://github.com/squaredev-io/gfm/releases/tag/v4.7.2) 5 days ago. I tested this on production... Did I miss something, is this behaviour ok?

**Comment by awareness481** [comment]
> We did a release (https://github.com/squaredev-io/gfm/releases/tag/v4.7.2) 5 days ago. I tested this on production... Did I miss something, is this behaviour ok?

Oh, it's certainly **not** ok then.

**Comment by chris-iliopoulos** [comment]
The account graph issue is resolved. The Cashflow Graphs issue remains.
