### ISSUE TITLE
Cashflow and Daily Balance don't look right

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#164]
![Screenshot 2023-02-01 at 17 58 44](https://user-images.githubusercontent.com/97880493/216096767-2ad3b304-f188-4363-97ba-a0a40effdfa4.png)
![Screenshot 2023-02-01 at 17 58 56](https://user-images.githubusercontent.com/97880493/216096773-0b789552-5437-47eb-a77d-40a09e5143e2.png)

`
Prediction of Income:  
        {
            "date": "2023-02-28T00:00:00.000Z",
            "dateStatus": "current",
            "amount": 0,
            "count": 0,
            "forecast": {
                "lower": 17035.76,
                "upper": 18333.53,
                "average": 17699.49,
                "metrics": {
                    "r2Score": 0.350233844243228,
                    "meanSquaredError": 1258869.0132,
                    "meanAbsoluteError": 780.4233333333333
                }
            }
        }

Prediction of Expenses: 
        {
            "date": "2023-02-28T00:00:00.000Z",
            "dateStatus": "current",
            "amount": -25.2,
            "count": 1,
            "forecast": {
                "lower": 36427.28,
                "upper": 38695.25,
                "average": 37540.88,
                "metrics": {
                    "r2Score": 0.5377951733628532,
                    "meanSquaredError": 4304991.838866668,
                    "meanAbsoluteError": 1432.2516666666668
                }
            }
        }`

**Comment by chris-iliopoulos** [comment]
@stavrostheocharis & @sinnec could you guys take a look at this issue?

**Comment by stavrostheocharis** [comment]
I had a quick check, unfortunately I believe that we may have sometimes such cases because the past data in most cases are not sufficient enough to have robust a realistic forecasts.

Maybe we could make it simple with just some averages and counting for outliers etc. (without complex methods that require large amounts of data points).

**Comment by chris-iliopoulos** [comment]
@stavrostheocharis this problem occurs now in these past few months and it did not like 6 months ago! And I can see it in my account which was working fine before that and which has sufficient data from at least a year ago ... so, something happened and it broke I think. ... for users that DO NOT have sufficient data I would understand though.

**Comment by stavrostheocharis** [comment]
Is it possible that maybe more same records are stored in DB and it actual gets them all (duplicates, etc.)?

**Comment by chris-iliopoulos** [comment]
no, it's the same with all new connections as well

**Comment by chris-iliopoulos** [comment]
UI-wise this is fixed

**Comment by awareness481** [comment]
Haven't been able to reproduce and this should be impossible to happen with the changes in the way we fetch cashflow data & the updates in wyre.
