### ISSUE TITLE
Client Side Error in transactions

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#166]
When i tryto see the transactions of my user i received the following error. It occurs when i try to scroll
![image](https://user-images.githubusercontent.com/64831585/216563871-ae0001e3-1fcf-41a9-8b8c-435669d6bfd6.png)

Screenshot from console
![image](https://user-images.githubusercontent.com/64831585/216564016-f0607b91-92da-4a2f-869e-d4e88f58e8a7.png)

**Comment by awareness481** [comment]
Closed in https://github.com/squaredev-io/GFM-UAT/issues/195
