### ISSUE TITLE
Floating Buttons disappear on certain screen sizes

### ISSUE THREAD

**Issue by geikosipentakis** [squaredev-io/GFM-UAT#167]
![Screenshot 2023-02-06 171036](https://user-images.githubusercontent.com/98013659/217008778-bafbba84-b79e-4c7d-9b05-72938c70a137.jpg)

**Comment by awareness481** [comment]
Users should be able to see the floating nav on smaller screens. Specifically for 1536px (which is 1920px laptops with default scaling on windows as far as I know) this is how it looks like

![image](https://user-images.githubusercontent.com/12380586/217858500-32b635bf-ca18-4c45-a276-6797ea2d39ce.png)

Do note that in some smaller screens, the text of the icon may been hidden as there is not enough space. Let me know if additional changes need to be done.

**Comment by awareness481** [comment]
@geikosipentakis Feel free to reopen or open a new issue if more changes are needed.
