### ISSUE TITLE
Error with pin setting

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#169]
![image](https://user-images.githubusercontent.com/64831585/217185036-c5f82821-b9ec-407b-87cd-3aca1be97b57.png)
The app asked for pin. Although i set the pin it doesn't allow me to go to next step.
![image](https://user-images.githubusercontent.com/64831585/217185142-c9785113-0fa7-4c47-8324-dcfbdbe9f9d2.png)
No error appeared on screen

**Comment by awareness481** [comment]
Accidentally closed this issue automatically. The issue with setting the pin should be resolved, @GeorgeVarvates if you still have the account you should be able to set the pin.

We still need handle an unexpected error, so im re-opening the issue for that

**Comment by awareness481** [comment]
We handle three different errors now, user not existing, user pin been already set and a generic error message.

looks like this
![image](https://user-images.githubusercontent.com/12380586/217859246-bb723010-b8a4-4e1b-953c-6daec7f20dd2.png)
