### ISSUE TITLE
Bank icons

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#170]
![image](https://user-images.githubusercontent.com/64831585/217824666-0963840a-69ab-48e7-9a33-406d88ebf372.png)

**Comment by awareness481** [comment]
Any chance you could retrieve the requested url? The url should be https://gfm.app.staging.squaredev.io/images/alpha-logo.png which should work (assuming this is alpha bank)

**Comment by GeorgeVarvates** [comment]
https://gfm.app.staging.squaredev.io/_next/image?url=%2Fimages%2Falphabank-logo.png&w=32&q=75

**Comment by awareness481** [comment]
@GeorgeVarvates should be fixed. Please let me know if you encounter this issue again.

**Comment by GeorgeVarvates** [comment]
It's ok now
