### ISSUE TITLE
Payment error

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#171]
![image](https://user-images.githubusercontent.com/64831585/217824948-147ab0f8-b5eb-41a7-9c71-bc73712eb896.png)
**BodyRequest**
Request URL: https://ofs.app.staging.squaredev.io/api/v1/payments
Request Method: POST
{
  "userId": "63e4cb0243e1958706b53cb6",
  "bankName": "alphabank",
  "fromAccountIban": "GR6601401270127002789007051",
  "toAccountIban": "GR9601401270127002371000725",
  "amount": 0.05,
  "description": "test1"
}
**Response**
{
  "code": "GENERIC_ERROR",
  "message": "Not Found",
  "provider": "S1"
}

**Comment by awareness481** [comment]
Was able to reproduce this error as well

**Comment by chris-iliopoulos** [comment]
> Was able to reproduce this error as well

@awareness481 
And what was it :) ? The amount or the description? Or sm else? because the generic error from S1 is usually an error with not much of a content to understand what's wrong

**Comment by awareness481** [comment]
> > Was able to reproduce this error as well
> 
> @awareness481 And what was it :) ? The amount or the description? Or sm else? because the generic error from S1 is usually an error with not much of a content to understand what's wrong

Oh, just the same error (from the screenshot) as well.
