### ISSUE TITLE
Set spending limit error

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#172]
![image](https://user-images.githubusercontent.com/64831585/217826034-8fa0afd9-fbc1-4864-806a-1dbbb304ace2.png)
![image](https://user-images.githubusercontent.com/64831585/217826359-e48e0659-5f1b-49de-86ea-0eadfa0f3ee4.png)

If i first set 0 limit and then i change it to another number the above error occurs

**Comment by awareness481** [comment]
You should be able to set the spending limit now, even if `0` was selected earlier.
