### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#175]
![image](https://user-images.githubusercontent.com/64831585/218043803-f2bec78c-2f43-40c0-8ad4-9a4d6b182d34.png)
After logging out , the stand alone login screen appears.If i reload the iframe the PIN screen appears, correctly

**Comment by chris-iliopoulos** [comment]
So, if I remember correctly you want the logout action, when the app is in iframe, to lead to the pin screen right?

**Comment by GeorgeVarvates** [comment]
Exactly
