### ISSUE TITLE
Transfer though GFM not shown in transactions 

### ISSUE THREAD

**Issue by nikosdouv** [squaredev-io/GFM-UAT#19]
I made a transfer between two linked accounts. I had the following issues:
I was not sure if the transfer was complete successfully- (confirmation message was missing or was not clear)
Then I checked my transactions list in GFM and the transfer was not there.
I had to logged in my web banking app to  realized that the transfer was completed successfully.

**Comment by chris-iliopoulos** [comment]
The first part of this issue about the confirmation message is indeed something that we should see and solve, so I propose we open an Issue about it. The second part of it is a known issue with getTransactions (@gcharis, @sinnec) that we are already trying to solve.
