### ISSUE TITLE
Clicking on "Προυπολογισμός" doesn't do anything

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#193]
![image](https://user-images.githubusercontent.com/64831585/221128661-fceb2d51-1ec9-462e-8f38-89c8a3cbab77.png)

**Comment by awareness481** [comment]
Closed automatically, let me verify that this is fixed once the deployment is ready

**Comment by awareness481** [comment]
This and https://github.com/squaredev-io/GFM-UAT/issues/192 should be working correctly now
