### ISSUE TITLE
Sometimes when pressing "Transactions" the following message appears

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#195]
![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/64831585/221132098-729b1cbc-4d1a-4171-9bc7-affcf7864a86.png)

**Comment by awareness481** [comment]
Ive likely found the source of this issue. Some transactions have a description value of `null` which is something we don't account for as we assume the field is a string value. Will have a fix soon.

**Comment by awareness481** [comment]
Should be fixed, feel free to reopen if the same issue occurs
