### ISSUE TITLE
Disconnected accounts

### ISSUE THREAD

**Issue by nikosdouv** [squaredev-io/GFM-UAT#22]
Although I have connected several accounts, each time i log in  i have to reconnect the accounts.
Since I connected the accounts once, I would expect to see them connected till the authorization expires or till i disconnect them

**Comment by chris-iliopoulos** [comment]
This is a problem with the refresh and the time it takes for the page to load the actual data ... it has nothing to do with the consents and reconnecting the accounts ... related with https://github.com/squaredev-io/gfm/issues/348

**Comment by chris-iliopoulos** [comment]
This issue is closed for now. The solution for this has been given and another will handle the 'new' problem - https://github.com/squaredev-io/GFM-UAT/issues/70
