### ISSUE TITLE
NBG add account issue - error screen

### ISSUE THREAD

**Issue by gtsiagas** [squaredev-io/GFM-UAT#223]
I added a new NBG account and upon completion of the procedure I got the following error screen.

![image](https://github.com/squaredev-io/GFM-UAT/assets/131853175/2f08db6a-19bb-49f0-baed-4dd03d3831b4)

Please let me know if you need anything else from my side.

**Comment by chris-iliopoulos** [comment]
@gtsiagas please delete your accounts from the Account page of GFM and try connecting again to see if it's still happening.

**Comment by gtsiagas** [comment]
@chris-iliopoulos it seems that worked ok now. I received the following success screen & not the error message.

![image](https://github.com/squaredev-io/GFM-UAT/assets/131853175/faf42d39-5b40-4a6c-b825-959aa7591c33)

**Comment by gtsiagas** [comment]
το επιχείρησα και με 2η τράπεζα (alpha bank) και πήρα το success message πάλι. Πριν το έιχα κάνει με την NBG.

fyi @chris-iliopoulos το έλεγξα στο test περιβάλλον (go-dev.s1cloud.net/). Δεν ξέρω αν παίζει κάποιο ρόλο αυτό.

**Comment by chris-iliopoulos** [comment]
Ωραία, μια χαρά ... Σε αυτό το περιβάλλον τα ελέγχουμε για την ώρα. Όταν ανέβει το GFM στο production environment του Prosvasis GO θα τα βλέπουμε από εκεί κατά τη διάρκεια του Friends n' Family. Από την πλευρά μας (Squaredev) είμαστε ήδη σε παραγωγικό περιβάλλον. Αν μπορέσει να δοκιμάσει και ο Βασίλης την σύνδεση και με την Πειραιώς (που έχει πρόβλημα για να τεστάρουμε κι ένα error case) αλλά και οποιαδήποτε άλλη τράπεζα έχει για να δούμε ότι είναι κι εκεί οκ τότε θα είμαστε τέλεια!
