### ISSUE TITLE
Add bank/account info in transactions page

### ISSUE THREAD

**Issue by nikosdouv** [squaredev-io/GFM-UAT#24]
When we display all the transactions analytically the user should be able to see from which account every transaction was made. Same for incoming/outgoing tabs.

**Comment by nikosdouv** [comment]
Same for payments page so that the user understands which account to debit/credit

**Comment by chris-iliopoulos** [comment]
Extra info for the Transactions Page would be: Account Description, Bank Name/Icon
Extra info for the Payments Page(Account Selector) would be: Account Description?, Bank Name/Icon, Currency?, Balance?
@ksiabani & @nikosdouv pls let's be more specific so we know what to implement.

**Comment by awareness481** [comment]
Duplicate with https://github.com/squaredev-io/GFM-UAT/issues/49
