### ISSUE TITLE
Show the expiration date of consent 

### ISSUE THREAD

**Issue by nikosdouv** [squaredev-io/GFM-UAT#26]
We should show the expiration date of the consent and also allow the user to manually cancel their consent for each connected account

**Comment by chris-iliopoulos** [comment]
@ksiabani we should discuss this further to settle to how and where this is going to be within the app

**Comment by chris-iliopoulos** [comment]
Show a list of the active consents (with status connected) in the My Account page (@ksiabani ui)

**Comment by ksiabani** [comment]
@chris-iliopoulos do we have time to wait for a suggestion from George (S1's UX guy)?

**Comment by chris-iliopoulos** [comment]
Yes we do, but it'd be great to have this in time (before the 15th of August)

**Comment by ksiabani** [comment]
I sent the guy the new Figma Matte kit, I will let him know that we need it by 5th of August (end of next week).

**Comment by awareness481** [comment]
https://www.figma.com/file/hl3biSsMK3Z8PlsCa8rLZs/GFM?node-id=209%3A455
https://github.com/squaredev-io/GFM-UAT/issues/50

**Comment by sinnec** [comment]
Partially completed by https://github.com/squaredev-io/gfm/pull/605
 The expiration date of consents is displayed but no option to cancel a consent.

**Comment by chris-iliopoulos** [comment]
Closing this for now ... when we implement the consent cancelation/refresh feature it will be on another issue.
