### ISSUE TITLE
Profit & Loss graph’s concept is not clear for the end-user.

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#31]
Maybe add a tooltip explaining what it's about

**Comment by chris-iliopoulos** [comment]
@ksiabani

**Comment by ksiabani** [comment]
The problem here is that the graph show two bars for each month. Somehow in the way it got messed up. The graph should show one bar per month. The value of the bar should be the difference between revenue and expenses (revenue - expenses). So the result will be either profit or loss.

**Comment by chris-iliopoulos** [comment]
@awareness481 I think this issue is ready for implementation, and I tagged you so you know
