### ISSUE TITLE
The Balance graph in the My Account page is not clear for the end-user.

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#36]
@ksiabani

**Comment by ksiabani** [comment]
The graph should show the balance of the sum of all accounts for the last 12 months. Then what is missing is just a tooltip to show the pointed value. Check an example here:

https://squaredev-io.github.io/matte/?path=/docs/components-structures-metric--metrics 

Let me know it this is clear

**Comment by chris-iliopoulos** [comment]
"The graph should show the balance of the sum of all accounts for the last 12 months" ... **for 12 months per month** continuously? @ksiabani

**Comment by chris-iliopoulos** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/97880493/179783882-16df53d4-7ccb-4db0-9988-cc7db2145b86.png)

After a discussion with @ksiabani we decided to solve the problem by going this route, but only with the X axis shown (months), without the Y axis and the grid and with a tooltip!

adding @awareness481 to the loop
