### ISSUE TITLE
More details on the accounts in the payments dropdown

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#41]

**Comment by awareness481** [comment]
Additional info: https://github.com/squaredev-io/GFM-UAT/issues/24#issuecomment-1173484909

**Comment by chris-iliopoulos** [comment]
@awareness481 After testing this I have 2 questions:
1. Is the balance ok in 'written form' or would we prefer to have it in numbers? (meaning 3000€ instead of 3 χιλ. €)
2. The bank icon only shows when selected and not in the dropdown, is this ok?

**Comment by awareness481** [comment]
> @awareness481 After testing this I have 2 questions:
> 
> 1. Is the balance ok in 'written form' or would we prefer to have it in numbers? (meaning 3000€ instead of 3 χιλ. €)
> 2. The bank icon only shows when selected and not in the dropdown, is this ok?

1. Yeah, I think your proposal is much better, I'll create an issue to track this
2. I found having an icon in both places to be a bit too much, we can definitely change this. I think it would be a good idea if S1 also commented on this, perhaps on the demo or in this issue
