### ISSUE TITLE
Sign in / Sign up Screen Redesign

### ISSUE THREAD

**Issue by geikosipentakis** [squaredev-io/GFM-UAT#42]
Design Proposals for Sign in / Sign up Screens:

https://www.figma.com/file/hl3biSsMK3Z8PlsCa8rLZs/GFM?node-id=74%3A34

**Comment by geikosipentakis** [comment]
@everybody Good job on that screen. Although there is an outline color on the box that is not included in the figma frame I shared.
The styling properties are:

background: #FFFFFF;
box-shadow: 0px 32px 72px rgba(0, 0, 0, 0.08);
border-radius: 8px;

+I hope in future implementations we can add "remember me" and forgot password;" functions.

Thank you in advance!

**Comment by sinnec** [comment]
Good morning @geikosipentakis . Thank you for the feedback.
I added the outline color on the box because it was in a (probably now deleted) figma frame with the border and some bubbles. I just kept the border because it seemed quite cool, but it can be easily removed!
