### ISSUE TITLE
After a payment the status modal doesn't redirect the user correctly and stays open

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#44]

**Comment by chris-iliopoulos** [comment]
This doesn't seem to work in the staging env. @awareness481 you remember fixing it right?

**Comment by awareness481** [comment]
Should have been fixed, I'll investigate this.

**Comment by awareness481** [comment]
Issue still persists, tracked in (https://github.com/squaredev-io/GFM-UAT/issues/66)
