### ISSUE TITLE
Changing transaction category takes several seconds and seems unresponsive

### ISSUE THREAD

**Issue by awareness481** [squaredev-io/GFM-UAT#52]
https://user-images.githubusercontent.com/12380586/184310626-b6a477a3-1255-4392-997d-28924ff16669.mp4

**Comment by sinnec** [comment]
Happened to me once (the first time I tried) but since that time, I can't reproduce the delay...

**Comment by chris-iliopoulos** [comment]
1. We should put a loader here for sure, so that the user knows the action is in progress.
2. We should time the process to see how long it takes for the update to happen in a test.

**Comment by sinnec** [comment]
Loader added with https://github.com/squaredev-io/gfm/pull/654. Need to see the cause of the initial delay.

**Comment by chris-iliopoulos** [comment]
The APi responds in ~7 secs in average which is a lot for what it does. Will try to add a couple of metrics in the API to see why this happens.

**Comment by chris-iliopoulos** [comment]
sample metrics:
Time elapsed finding existing transaction:  5
Time elapsed updating transaction:  2

from a couple of tests it seems that the findOne takes more time than it should...

**Comment by chris-iliopoulos** [comment]
After removing a find that was not necessary we now get these metrics:
Time elapsed updating transaction:  5
Time elapsed updating transaction:  9
Time elapsed updating transaction:  3
Time elapsed updating transaction:  7
Time elapsed updating transaction:  6

So a possible solution could be to create a new index with the field that we use to get the document from the DB or change the filter and use a field that has an index already (like _id).
