### ISSUE TITLE
Best Customers Revenue graph

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#56]
![Screenshot 2022-08-17 at 17 09 48](https://user-images.githubusercontent.com/97880493/185156081-902f860c-b167-4f16-a983-8a77f8fb3454.png)

I think that the word 'Χρέος΄ here is wrong ... the graph is about Revenue which if I'm not mistaken is the exact opposite.

& there's a bug when you choose 1M in the filters there's a loader that shows nothing

**Comment by awareness481** [comment]
This could happen when there are no customers for a specific time period, I'm working on a fix atm.
