### ISSUE TITLE
Budget amounts and graph

### ISSUE THREAD

**Issue by sinnec** [squaredev-io/GFM-UAT#60]
If you add an amount to a category, you can't edit this category to the full budget amount (even if no other categories are set).

https://user-images.githubusercontent.com/48223149/185386488-bfc59b49-b859-4fb3-95b8-d617456f245d.mov

Also I quite don't understand the graph and from when the spending amounts are taken from. Is it current month, last 30 days or something else?

 I've set budget limit to 20.000 euros and the other category to 10.000 euros. I might have spent 2,7k last 30 days but no way I've spent 10.000!!! Also the set category doesn't appear.
<img width="1033" alt="Screenshot 2022-08-18 at 14 22 28" src="https://user-images.githubusercontent.com/48223149/185387327-4554d53a-11dd-4d03-b7f5-69f36f3be635.png">
<img width="973" alt="Screenshot 2022-08-18 at 14 22 44" src="https://user-images.githubusercontent.com/48223149/185387349-ee386b32-09f5-4ff0-9698-347b5f038b0a.png">

**Comment by chris-iliopoulos** [comment]
![Screenshot 2022-09-06 at 13 52 26](https://user-images.githubusercontent.com/97880493/188617470-7ee03901-3ba4-4b7b-8016-faee10588fa8.png)
 Tried to lower my budget (which was higher) and then tried to 'delete' a category by putting 0 in the field but this happened. No error shows in the field but there's an error in the console.
