### ISSUE TITLE
No prediction for the following two months

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#62]
![image](https://user-images.githubusercontent.com/64831585/185581353-ca9b9c01-04ee-4c2f-adeb-d40221f9a98a.png)
There is no prediction for the following two months

**Comment by awareness481** [comment]
Was this on a new account? The predictions are available within 5 mins (usually 1-2 mins) of someone adding an account

**Comment by GeorgeVarvates** [comment]
It's an old connection.

**Comment by awareness481** [comment]
cc @chris-iliopoulos can having an old account cause such issues? (since there were breaking changes with `withAnalytics: true`)

**Comment by GeorgeVarvates** [comment]
![image](https://user-images.githubusercontent.com/64831585/185601713-e35a8f08-ada3-42ba-b6c6-4704bc71c2a4.png)
Furthermore if i hover over June , it says "εσοδα πρόβλεψη" and "εξοδα πρόβλεψη"

**Comment by chris-iliopoulos** [comment]
> cc @chris-iliopoulos can having an old account cause such issues? (since there were breaking changes with `withAnalytics: true`)

Yes it does .. that's why I asked for the userId in another comment.

**Comment by chris-iliopoulos** [comment]
The "πρόβλεψη" literal , if there's no prediction to show should not be there, that's a minor bug. But the user not having a prediction at all is because the analytics have not been executed for said user.

**Comment by GeorgeVarvates** [comment]
![image](https://user-images.githubusercontent.com/64831585/186094043-df009485-e3dd-4319-b47a-9b6ff744542b.png)
Prediction is ok now, but July is missing

**Comment by chris-iliopoulos** [comment]
Cannot reproduce this issue. Another open issue with missing transactions already exist and has to do with invalid consents creating this problem in the scheduled refresh jobs. Will be solved through another issue.
