### ISSUE TITLE
Daily balance chart

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#63]
![image](https://user-images.githubusercontent.com/64831585/185581520-3e9fb7d0-5be8-4bb9-8014-d58b2344d272.png)
Daily balance is empty

**Comment by chris-iliopoulos** [comment]
too little info to see what could be wrong here ... pls give some extra information like userId

**Comment by GeorgeVarvates** [comment]
userId = 62be9581f7b0f42c93378f6d
it also happens to Nikos account

**Comment by chris-iliopoulos** [comment]
This will be solved within the next hour ... your user (and others with the same issue) is old and was not configured properly for analytics.

**Comment by GeorgeVarvates** [comment]
Nikos userid  = 624adbac30fb1a0dd846a993

**Comment by chris-iliopoulos** [comment]
> 624adbac30fb1a0dd846a993

u sure? because I can't find a userId like that in production...

**Comment by GeorgeVarvates** [comment]
![image](https://user-images.githubusercontent.com/64831585/186094628-5a69db15-26d0-4385-a259-9b8b27f63cad.png)
I can see the chart now. However i think that this red line on the bottom shouldn't be visible when the value is positive
