### ISSUE TITLE
Disconnect ERP

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#64]
There is no way to disconnect my GO connection

**Comment by chris-iliopoulos** [comment]
No discussions where made on a disconnect ERP feature, much like disconnect a bank. @ksiabani ?

**Comment by ksiabani** [comment]
True, it makes sense for both, though.

**Comment by chris-iliopoulos** [comment]
@geikosipentakis we will need some UI/UX for this one ... if you want help or feel the need to discuss this further please let me know
