### ISSUE TITLE
Payment status message cannot be closed

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#66]
![Screenshot 19-08-2022 122029](https://user-images.githubusercontent.com/64831585/185596289-204e25dd-e528-475b-860d-dae40dcb78f2.jpg)
After any payment, no matter if the status is successful or not, we cannot close the message.  As a result, i have to refresh the whole site

**Comment by chris-iliopoulos** [comment]
This bug has been resolved already ... pls let me check it though.
