### ISSUE TITLE
Duplicate transactions

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#67]
![image](https://user-images.githubusercontent.com/64831585/185596807-d54ca77c-2c72-4f22-93ca-ec77a697fbcd.png)

**Comment by chris-iliopoulos** [comment]
pls share some more info on how and when you saw these duplicates... was it right after the connect or after a while?

**Comment by GeorgeVarvates** [comment]
It's an old account connection. It just happens. I didn't do something specific

**Comment by GeorgeVarvates** [comment]
Seems to be ok now

**Comment by GeorgeVarvates** [comment]
![image](https://user-images.githubusercontent.com/64831585/186420444-dd8be27b-df41-40bb-9edd-467295baa84a.png)
still happens. i didn't do something special to reproduce it. I just added a new connection

**Comment by chris-iliopoulos** [comment]
We already have another open issue for this ... https://github.com/squaredev-io/GFM-UAT/issues/71 ... so it's tracked.
