### ISSUE TITLE
Notifications update

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#68]
![image](https://user-images.githubusercontent.com/64831585/185605288-4d92287e-5555-4ccb-ba46-42452d8078f5.png)
Last notifications update -> 2 months ago

**Comment by chris-iliopoulos** [comment]
same issue ... all the cron jobs related with Analytics wouldn't run if your user is not configured correctly

**Comment by GeorgeVarvates** [comment]
Solved
