### ISSUE TITLE
Transaction details

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#69]
![image](https://user-images.githubusercontent.com/64831585/185606591-97f0a19a-b24d-423b-ba7f-8e12d664052f.png)
After clicking on a transaction, it redirects me to an empty screen

**Comment by awareness481** [comment]
Tracked here: https://github.com/squaredev-io/GFM-UAT/issues/58 (closing it as duplicate), thanks!
