### ISSUE TITLE
Cannot add bank connection 

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#7]
No matter which bank i choose, the login screen doensn't appear. 
The request that fails: 
`https://ofs.app.squaredev.io/api/v1/consents`

The response i get is the following 

`{"status":500,"data":{"error":"","provider":true}}`

and the payload is the following
`{
  "bankName": "alphabank",
  "callbackUrl": "https://gfm.app.squaredev.io/dashboard/connected",
  "userId": "62985bd17fab2ea1a4355a8d"
}`

**Comment by chris-iliopoulos** [comment]
Happens probably because of consents..

**Comment by chris-iliopoulos** [comment]
Cannot Reproduce. problem has to do with consents, which is another open issue atm
