### ISSUE TITLE
Full Transaction classification returns duplicate transactions

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#71]
Full Transaction Classification flow from WYRE returns duplicate transactions (accounts & cards) that are pre-existing from the PSD2 bank responses. This means that WYRE doesn't reconcile them correctly in order to remove duplicates.

**Comment by stavrostheocharis** [comment]
Wyre does not dismiss one of the duplicated transactions, it just classifies everything and finds which are duplicated (eg. "duplicated_with" field corresponds to the appropriate duplicated transaction (the corresponding id). I think that this should be handled by the visualization we want in FE (show only the accounts that include also the cards) and maybe show separated the cards?

**Comment by chris-iliopoulos** [comment]
@ksiabani @awareness481 we should probably discuss a solution and maybe a new Feature ...

**Comment by alexKarvounis** [comment]
@chris-iliopoulos we remove it from the Solutions board. Please add it if you need something from Solutions

**Comment by chris-iliopoulos** [comment]
https://github.com/squaredev-io/wyre-v2/issues/20
