### ISSUE TITLE
After connecting a second Bank the Transactions List doesn't seem to update the transactions from the new bank even though the transactions exist in the DB

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#78]

**Comment by chris-iliopoulos** [comment]
Request URL: https://ofs.app.staging.squaredev.io/api/v1/transactions/enriched?userId=6303832a942999159a249f43&from=2021-08-22&to=2022-08-22

this seems weird it shouldn't give the dates params in the enriched api...

**Comment by awareness481** [comment]
This is likely happening because we're not invalidating the `enriched` transactions

https://github.com/squaredev-io/gfm/blob/1e35075ca9c53590232ad27374cd3cc61d99ffdc/src/app/services/api.ts#L182

Edit: Actually thats probably not it since `enriched` has ` providesTags: ["transactions"]`

**Comment by chris-iliopoulos** [comment]
This issue seems to be ok as far as the api response goes and the Transactions List after refreshing the page. I think there's two issues that we should consider here as far as the GFM (front) goes. First of all we probably need a loader in the Transactions List to show that we should wait for the api to fetch new stuff (because the old stuff's already there and it's misleading) and second I think we should somehow refresh the /enriched transactions or allow the user to always fetch the /enriched stuff when clicking the Transactions button up top! (now when you are already inside the Transactions list if you click the button it does nothing) ... @awareness481 what say ye?

**Comment by chris-iliopoulos** [comment]
*Small note here after checking the '/enriched' API ... This could cause a problem because the enriched transactions api will always filter the "fresh" ones (the ones that haven't been analysed from WYRE yet, the transactions that don't have the 'category' field), so they won't show up in the Transactions Page in time (that causes the small delay in what the user sees). Should investigate more.
