### ISSUE TITLE
Onboarding last step - Missing button

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#82]
![gfm-onboarding-3step](https://user-images.githubusercontent.com/64831585/186413167-b841e165-a9e4-46c2-96a7-1ff1dcca5344.jpg)
What button?

**Comment by chris-iliopoulos** [comment]
Outside of this modal hahaha ... anyways this is part of a redesign issue that's opened for the onboarding process so I'll link it here and close this one. https://github.com/squaredev-io/GFM-UAT/issues/43
