### ISSUE TITLE
Error after adding a new connection

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#83]
![image](https://user-images.githubusercontent.com/64831585/186413896-53bc2f99-3a0f-4c18-baa5-b0e3af2ac3a2.png)
After adding a new bank this error message appears. However the bank connection seems to be ok

**Comment by chris-iliopoulos** [comment]
Indeed this started happening this past week , it does it to me too... will see to it!

**Comment by awareness481** [comment]
This has been fixed. Feel free to re-open if the error reappears.
