### ISSUE TITLE
Long loading times and no prediction

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#84]
![image](https://user-images.githubusercontent.com/64831585/186430863-23a69cae-7bbd-4537-94d8-30e551bfce23.png)
It keeps loading for a long time. When it finally loads there are no prediction months

![image](https://user-images.githubusercontent.com/64831585/186431230-b615f215-fa36-4baa-83f9-a9abcb223c22.png)
i have created the consents an hour ago (maybe more)

**Comment by awareness481** [comment]
This indicates that no cashflow was generated, therefore we used the bank transactions API to generate the data. @chris-iliopoulos can you take a look at the logs?

**Comment by chris-iliopoulos** [comment]
Sure , this is definitely it. It takes some time for the flow to return a cashflow, all we can do is somehow let the user know it's been processed ... @GeorgeVarvates please check again to see if the cashflow has been created and if not I will check the logs to see if there's something wrong.

**Comment by chris-iliopoulos** [comment]
I see that the cashflow has been generated for your user. I am not sure why it took so long but this is not the normal case as we have tried it many many times and it always takes only 5 minutes max to generate. Will not close this issue and will keep an eye to it!

**Comment by GeorgeVarvates** [comment]
@chris-iliopoulos  sorry for my late response. Yes the cashflow is ok now, but it took too much time

**Comment by GeorgeVarvates** [comment]
I tried again with a clean GFM account. After 10 minutes i see no chart and no transactions. Balances are ok.

**Comment by chris-iliopoulos** [comment]
this is probably connected with this issue: https://github.com/squaredev-io/GFM-UAT/issues/93 will check again after this is resolved

**Comment by chris-iliopoulos** [comment]
This should be solved now because of this https://github.com/squaredev-io/GFM-UAT/issues/93
