### ISSUE TITLE
When do we consider a transaction as a recurring?

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#85]
![image](https://user-images.githubusercontent.com/64831585/186661082-259decea-f67c-4b6f-82b7-000a9d4b2827.png)
The system characterizes these transactions as recurring. They are simple tests
However i have some recurring transactions (like Netflix, Disney+) and the transaction is not characterized as such
![image](https://user-images.githubusercontent.com/64831585/186661953-143b96c1-337b-478b-954b-86c9e8a11873.png)
![image](https://user-images.githubusercontent.com/64831585/186663592-0e759fd4-4925-430e-9b01-2c81c27aa072.png)

**Comment by chris-iliopoulos** [comment]
@stavrostheocharis can answer this better...

**Comment by stavrostheocharis** [comment]
**1+3 rules are being applied for recurring transactions:**

There are needed at least 3 similar transactions

Similar transactions are considered the following:
- The amounts should match with no more than a slight variation of 0.05%
- The dates should be continuous in terms of months (including the current month) and the days should have no more than a variation of 3
- The description similarity should be at 70% based on an adjusted text similarity algorithm of ours

For the above, I found the bug for the incoming transactions that seem as recurring (it was a bug based on the fact that all the transactions are similar and on the same exact day). I have fixed it locally, I need to merge it.

For the two other expenses transactions, I believe that one, or more of the above rules do not apply.

**Comment by stavrostheocharis** [comment]
@chris-iliopoulos, I opened a corresponding issue in Wyre: https://github.com/squaredev-io/wyre-v2/issues/21

**Comment by GeorgeVarvates** [comment]
![image](https://user-images.githubusercontent.com/64831585/186834649-35aaf774-eef2-464a-99a9-de7357f3afac.png)
These are my 7 last netflix payments. I think all the rules apply

**Comment by stavrostheocharis** [comment]
Yes indeed all the rules apply. 

@chris-iliopoulos it is weird because I check it locally into wyre and it works indicating them as recurring.
We need to investigate it more.

**Comment by chris-iliopoulos** [comment]
@GeorgeVarvates can you please confirm if this issue persists? Thank you.

**Comment by GeorgeVarvates** [comment]
Seems to be ok now for the majority of transactions. The only issue that i can find now is that a netflix transaction is not tagged as recurring , but the problem here is that the description of the payment is a bit different from the others

netflix.com vs netflix internationa

![image](https://user-images.githubusercontent.com/64831585/194821827-cb11c74e-4810-4dbc-a2d8-2c878e6f5c0f.png)
![image](https://user-images.githubusercontent.com/64831585/194821881-57d03c30-1ca8-453f-8519-999e9589b507.png)
![image](https://user-images.githubusercontent.com/64831585/194821995-97632f32-e9d2-4b0b-8a77-dd46450c8df0.png)

**Comment by chris-iliopoulos** [comment]
@stavrostheocharis any thoughts on this one?

**Comment by stavrostheocharis** [comment]
Actually, the case here is that the "netflix.com"  "netflix international" have a similarity score below our default threshold and are not considered the same. I will have a look, in order to reduce our default threshold for such cases, but I want to be sure that we will not break something else.

**Comment by chris-iliopoulos** [comment]
closing this one as stale because there doesn't seem to be a problem with it atm.
