### ISSUE TITLE
After pressing "back" from details screen , it scrolls to top

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#86]
1. Scroll a lot
2. Select a transaction
3. Details screen appears
4. Press back
5. It takes me to top and i have to scroll again to get to the point i was in step 2

**Comment by chris-iliopoulos** [comment]
@awareness481 the 'problem' is still here

**Comment by awareness481** [comment]
Yeah, I just checked since I saw the issue was reopened. Seems it only works correctly for some transactions for some reason.

**Comment by awareness481** [comment]
Will need more investigation as it doesn't happen always. Unsure, as of now, if a fix will be available this sprint.
