### ISSUE TITLE
Error during payment initiation

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#9]
I choose two of my accounts and i get the following error message
![Screenshot 06_14_2022 15_02_11](https://user-images.githubusercontent.com/64831585/173572566-c1719ad2-b9a0-41e8-82aa-f5963d034da5.png)

**Comment by chris-iliopoulos** [comment]
Try a bigger amount , something like 1€ ?

**Comment by GeorgeVarvates** [comment]
Now the app doesn't load any data

**Comment by GeorgeVarvates** [comment]
If i choose a bigger amount , it works. However there is a message that tells me that i can  send 0.01 or more
![Screenshot 06_15_2022 12_36_21](https://user-images.githubusercontent.com/64831585/173796383-89854ea7-2ff8-4e71-a702-65f85041be5b.png)

Now the behavior is different. If i choose to send 0.01, it redirects me to the main page and it changes my language from greek to english

**Comment by chris-iliopoulos** [comment]
In the Greek version of the app the message is wrong. (when hovering)

**Comment by chris-iliopoulos** [comment]
Case with 0,01€ and description 'test' -> error:
data: "Cannot read properties of undefined (reading '0')"
error: "SyntaxError: Unexpected token C in JSON at position 0"
originalStatus: 500
status: "PARSING_ERROR"
