### ISSUE TITLE
Loader without any connections

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#92]
![image](https://user-images.githubusercontent.com/64831585/187372721-d45ef24e-a611-4745-a856-ffad4a9e1897.png)
I have ust created my GFM account and i don't have any connections, but the loader keeps spinning. Perhaps another message should appear instead, informing the user that he has no data yet

**Comment by chris-iliopoulos** [comment]
This problem will be solved once the onboarding redesign will be implemented because it will lead you to connect a bank right from the start.
