### ISSUE TITLE
Wrong prediction

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#97]
![image](https://user-images.githubusercontent.com/64831585/187922243-3ad20e1f-92dd-40c2-ad20-2d5530aa2b8a.png)
The screenshot was taken today 1/9/2022
The chart is stuck in August. September should be the current month with both live and prediction columns and November should be the last prediction month
Perhaps the issue occurs because i have connected a eurobank account and the consent is invalid

**Comment by GeorgeVarvates** [comment]
Although i refreshed the consent nothing has changed. Furthermore it seems that the charts are stuck to 31/8/2022
![image](https://user-images.githubusercontent.com/64831585/187931044-54fc1e63-04f5-41fd-9c8d-62adb42bed0a.png)

**Comment by chris-iliopoulos** [comment]
linked with this issue: https://github.com/squaredev-io/GFM-UAT/issues/93

**Comment by chris-iliopoulos** [comment]
@GeorgeVarvates can you please confirm that this issue still persists? Thank you.

**Comment by GeorgeVarvates** [comment]
It seems ok now
