### ISSUE TITLE
Different values for same categories

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#98]
![image](https://user-images.githubusercontent.com/64831585/187933693-f76c7057-7854-4d14-9541-3620b8235dea.png)
![image](https://user-images.githubusercontent.com/64831585/187933724-e62d36d7-a9b3-4605-b3f7-0675ae4fccf0.png)
For the same category i get different numbers.

**Comment by chris-iliopoulos** [comment]
The pie chart above is an analysis of your expenses for the past 12 months. The bar chart below is from the tax deduction I suppose which shows you your expenses per category since the start of the current year, so it's normal.
